//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramadorCS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SiempreEncima {
            get {
                return ((bool)(this["SiempreEncima"]));
            }
            set {
                this["SiempreEncima"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ActivarAero {
            get {
                return ((bool)(this["ActivarAero"]));
            }
            set {
                this["ActivarAero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte PosRadioAccion {
            get {
                return ((byte)(this["PosRadioAccion"]));
            }
            set {
                this["PosRadioAccion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PosTabPpal {
            get {
                return ((byte)(this["PosTabPpal"]));
            }
            set {
                this["PosTabPpal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan HoraCuentaAtras {
            get {
                return ((global::System.TimeSpan)(this["HoraCuentaAtras"]));
            }
            set {
                this["HoraCuentaAtras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-01-01")]
        public global::System.DateTime HoraA1Hora {
            get {
                return ((global::System.DateTime)(this["HoraA1Hora"]));
            }
            set {
                this["HoraA1Hora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VerMonitorizacion {
            get {
                return ((bool)(this["VerMonitorizacion"]));
            }
            set {
                this["VerMonitorizacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PosRibbonTab {
            get {
                return ((byte)(this["PosRibbonTab"]));
            }
            set {
                this["PosRibbonTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PosRadioCarga {
            get {
                return ((byte)(this["PosRadioCarga"]));
            }
            set {
                this["PosRadioCarga"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EsMayorComboCargaEquipo {
            get {
                return ((bool)(this["EsMayorComboCargaEquipo"]));
            }
            set {
                this["EsMayorComboCargaEquipo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int DatosIntegerInputCargaEquipo {
            get {
                return ((int)(this["DatosIntegerInputCargaEquipo"]));
            }
            set {
                this["DatosIntegerInputCargaEquipo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MinutosIntegerInputCargaEquipo {
            get {
                return ((int)(this["MinutosIntegerInputCargaEquipo"]));
            }
            set {
                this["MinutosIntegerInputCargaEquipo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForzarCierre {
            get {
                return ((bool)(this["ForzarCierre"]));
            }
            set {
                this["ForzarCierre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReinicioAppsReg {
            get {
                return ((bool)(this["ReinicioAppsReg"]));
            }
            set {
                this["ReinicioAppsReg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PosRadioEnergia {
            get {
                return ((byte)(this["PosRadioEnergia"]));
            }
            set {
                this["PosRadioEnergia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PosComboAlimentacion {
            get {
                return ((byte)(this["PosComboAlimentacion"]));
            }
            set {
                this["PosComboAlimentacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PosComboPlanEnergia {
            get {
                return ((byte)(this["PosComboPlanEnergia"]));
            }
            set {
                this["PosComboPlanEnergia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EsMasComboBateria {
            get {
                return ((bool)(this["EsMasComboBateria"]));
            }
            set {
                this["EsMasComboBateria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PosRadioSecBat {
            get {
                return ((bool)(this["PosRadioSecBat"]));
            }
            set {
                this["PosRadioSecBat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:10:00")]
        public global::System.TimeSpan TiempoRestanteBateria {
            get {
                return ((global::System.TimeSpan)(this["TiempoRestanteBateria"]));
            }
            set {
                this["TiempoRestanteBateria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte PorcentajeRestanteBateria {
            get {
                return ((byte)(this["PorcentajeRestanteBateria"]));
            }
            set {
                this["PorcentajeRestanteBateria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DuranteAlimentacion {
            get {
                return ((bool)(this["DuranteAlimentacion"]));
            }
            set {
                this["DuranteAlimentacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MinutosIntegerInputAlimentacion {
            get {
                return ((int)(this["MinutosIntegerInputAlimentacion"]));
            }
            set {
                this["MinutosIntegerInputAlimentacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VerOverlayIcons {
            get {
                return ((bool)(this["VerOverlayIcons"]));
            }
            set {
                this["VerOverlayIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JumpListON {
            get {
                return ((bool)(this["JumpListON"]));
            }
            set {
                this["JumpListON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PosRadioRed {
            get {
                return ((bool)(this["PosRadioRed"]));
            }
            set {
                this["PosRadioRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PosCombo1BajadaRed {
            get {
                return ((bool)(this["PosCombo1BajadaRed"]));
            }
            set {
                this["PosCombo1BajadaRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PosComboMayorRed {
            get {
                return ((bool)(this["PosComboMayorRed"]));
            }
            set {
                this["PosComboMayorRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CantidadUds1IntegerInputRed {
            get {
                return ((int)(this["CantidadUds1IntegerInputRed"]));
            }
            set {
                this["CantidadUds1IntegerInputRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte PosCombo1UdsRed {
            get {
                return ((byte)(this["PosCombo1UdsRed"]));
            }
            set {
                this["PosCombo1UdsRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PosCombo2BajarRed {
            get {
                return ((bool)(this["PosCombo2BajarRed"]));
            }
            set {
                this["PosCombo2BajarRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CantidadUds2IntegerInputRed {
            get {
                return ((int)(this["CantidadUds2IntegerInputRed"]));
            }
            set {
                this["CantidadUds2IntegerInputRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte PosCombo2UdsRed {
            get {
                return ((byte)(this["PosCombo2UdsRed"]));
            }
            set {
                this["PosCombo2UdsRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PosComboAdaptador {
            get {
                return ((byte)(this["PosComboAdaptador"]));
            }
            set {
                this["PosComboAdaptador"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DuranteRed {
            get {
                return ((bool)(this["DuranteRed"]));
            }
            set {
                this["DuranteRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MinutosIntegerInputRed {
            get {
                return ((int)(this["MinutosIntegerInputRed"]));
            }
            set {
                this["MinutosIntegerInputRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FMRemitente {
            get {
                return ((string)(this["FMRemitente"]));
            }
            set {
                this["FMRemitente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FMUsuario {
            get {
                return ((string)(this["FMUsuario"]));
            }
            set {
                this["FMUsuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FMContrasena {
            get {
                return ((string)(this["FMContrasena"]));
            }
            set {
                this["FMContrasena"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FMHost {
            get {
                return ((string)(this["FMHost"]));
            }
            set {
                this["FMHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public ushort FMPuerto {
            get {
                return ((ushort)(this["FMPuerto"]));
            }
            set {
                this["FMPuerto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FMSSL {
            get {
                return ((bool)(this["FMSSL"]));
            }
            set {
                this["FMSSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FMAsunto {
            get {
                return ((string)(this["FMAsunto"]));
            }
            set {
                this["FMAsunto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FMCuerpo {
            get {
                return ((string)(this["FMCuerpo"]));
            }
            set {
                this["FMCuerpo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FMDestinatario {
            get {
                return ((string)(this["FMDestinatario"]));
            }
            set {
                this["FMDestinatario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FMCcCco {
            get {
                return ((string)(this["FMCcCco"]));
            }
            set {
                this["FMCcCco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FMPosComboCcCco {
            get {
                return ((bool)(this["FMPosComboCcCco"]));
            }
            set {
                this["FMPosComboCcCco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte FMPosComboPreconfiguracion {
            get {
                return ((byte)(this["FMPosComboPreconfiguracion"]));
            }
            set {
                this["FMPosComboPreconfiguracion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FMArchivoAdjunto {
            get {
                return ((string)(this["FMArchivoAdjunto"]));
            }
            set {
                this["FMArchivoAdjunto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FMConfiguracionCorrecta {
            get {
                return ((bool)(this["FMConfiguracionCorrecta"]));
            }
            set {
                this["FMConfiguracionCorrecta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FEArchivoSeleccionado {
            get {
                return ((string)(this["FEArchivoSeleccionado"]));
            }
            set {
                this["FEArchivoSeleccionado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aracne 3.0.1")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FEConfiguracionCorrecta {
            get {
                return ((bool)(this["FEConfiguracionCorrecta"]));
            }
            set {
                this["FEConfiguracionCorrecta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte FEIndiceFiltro {
            get {
                return ((byte)(this["FEIndiceFiltro"]));
            }
            set {
                this["FEIndiceFiltro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FEDirectorioInicial {
            get {
                return ((string)(this["FEDirectorioInicial"]));
            }
            set {
                this["FEDirectorioInicial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte PosComboUds {
            get {
                return ((byte)(this["PosComboUds"]));
            }
            set {
                this["PosComboUds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PosComboDesConexionUd {
            get {
                return ((bool)(this["PosComboDesConexionUd"]));
            }
            set {
                this["PosComboDesConexionUd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SiUdEs {
            get {
                return ((bool)(this["SiUdEs"]));
            }
            set {
                this["SiUdEs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PosComboTipoUd {
            get {
                return ((byte)(this["PosComboTipoUd"]));
            }
            set {
                this["PosComboTipoUd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SiUdTieneCapacTot {
            get {
                return ((bool)(this["SiUdTieneCapacTot"]));
            }
            set {
                this["SiUdTieneCapacTot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PosComboMayorUd {
            get {
                return ((bool)(this["PosComboMayorUd"]));
            }
            set {
                this["PosComboMayorUd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte CantidadUdsIntegerInputUd {
            get {
                return ((byte)(this["CantidadUdsIntegerInputUd"]));
            }
            set {
                this["CantidadUdsIntegerInputUd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte PosComboMagnitudUd {
            get {
                return ((byte)(this["PosComboMagnitudUd"]));
            }
            set {
                this["PosComboMagnitudUd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PosComboYOUd {
            get {
                return ((bool)(this["PosComboYOUd"]));
            }
            set {
                this["PosComboYOUd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RetardarAcciones {
            get {
                return ((bool)(this["RetardarAcciones"]));
            }
            set {
                this["RetardarAcciones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public short SegundosIntegerInputRetardarAcciones {
            get {
                return ((short)(this["SegundosIntegerInputRetardarAcciones"]));
            }
            set {
                this["SegundosIntegerInputRetardarAcciones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizarBandeja {
            get {
                return ((bool)(this["MinimizarBandeja"]));
            }
            set {
                this["MinimizarBandeja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IniciarConWindows {
            get {
                return ((bool)(this["IniciarConWindows"]));
            }
            set {
                this["IniciarConWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte Paletas {
            get {
                return ((byte)(this["Paletas"]));
            }
            set {
                this["Paletas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte EstiloTabControl {
            get {
                return ((byte)(this["EstiloTabControl"]));
            }
            set {
                this["EstiloTabControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IniciarMinimizado {
            get {
                return ((bool)(this["IniciarMinimizado"]));
            }
            set {
                this["IniciarMinimizado"] = value;
            }
        }
    }
}
